<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: "50dp"
        spacing: "30dp"

        MDIconButton:
            icon: "cog"
            pos_hint: {"rigth": 1, "top": 1}
            icon_size: "50dp"

        MDlabel:
            text: "SHOOTER"
            haling: "center"
            font_size: "60sp"

        Image:
            source: "assets/images/2089dbc0-d6f2-43c5-86a8-109958648d9e.jpg"

        MDButton:
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            on_press:
                root.manager.current = "game"

            MDButtonText:
                text: "PLAY"
                font_size: "80sp"
                theme_text_color: "Custom"
                text_color: "white"

<Ship@Image>:
    source: "assets/images/rocket.png"
    size_hint: None, None
    size: dp(100), dp(300)

<GameScreen>:
    FloatLayout:
        FloatLayout:
            id: game
            FloatLayout:
                id: back
            FloatLayout:
                id: front
                Ship:
                    id: ship
                    center: root.center

        FloatLayout:
            id: interface