<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: "50dp"
        spacing: "30dp"

    MDIconButton:
        icon: "cog"
        pos_hint: {"rigth": 1, "top": 1}
        icon_size: "50dp"

    MDlabel:
        text: "SHOOTER"
        haling: "center"
        font_size: "60sp"

    image:
        source: "assets/images/2089dbc0-d6f2-43c5-86a8-109958648d9e.jpg"